name: Tagging

on:
  push:
    branches:
      - dev

jobs:
  tagging:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: TriPSs/conventional-changelog-action@v3
        name: Changelog
        id: changelog
        with:
          git-user-nane: "{{ Username }}"
          git-user-email: "{{ Email }}"
          git-message: "chore(release): {version}"